version: "3.11"
networks:
  my_network:
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      my_network:


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/rms_database
      - TMDB_API_KEY=c977679de6afcab8e7a9312fea820565
    depends_on:
      - mongodb
    volumes:
      - ./backend:/backend
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      my_network:


volumes:
  mongo-data:
